---
abstract: 'manipulate PFILES path for IRAF Compatible parameter files'
author: 'The Smithsonian Astrophysical Observatory'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.67'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Config-PFiles-Path
no_index:
  directory:
    - inc
    - t
requires:
  Sub::Uplevel: 0
version: 0.02
